dependencies:
- name: alarm-ticket-generation
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: gv-python-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: test-jenkinsx-cicd-1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
